version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fluffy-backend
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - fluffy-network

  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    container_name: fluffy-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - fluffy-network

  mongo:
    image: mongo:6.0
    container_name: fluffy-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fluffy-network

networks:
  fluffy-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local